version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: ee
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    # help persist local mysql data
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      # ./src is the expression engine files unzipped
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm
    build: .
    volumes:
      - ./src:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on: 
      - db

volumes: 
  db_data: